Added Import Limit
bookwyrm-social/bookwyrm pull request #2511
Opened 2022-12-15 22:49 UTC by Giebisch

Fixes #2429 

It's not ready yet, as I'm still running into 2 bugs using this feature. Also tests are not available yet, but I thought it's still useful to create a draft PR so you can already give feedback on the implementation.

**Todo**
- [ ] Bugfix
- [ ] Add tests

The admin can set a limit and the user can see how many book imports he has left. The import button is disabled when there are no more imports remaining.

**Admin view**
![import_limit](https://user-images.githubusercontent.com/39874595/207983128-240f4a30-d0da-4165-8dd9-124f951d3708.PNG)

**User view**
![allowed_imports](https://user-images.githubusercontent.com/39874595/207983123-7fe44c87-a6d1-467e-9c83-814a166145b3.PNG)

2022-12-16 21:00 UTC, mouse-reeve commented
Sorry for making your tests even more busted with that commit! I believe all you need to do is create a merge migration to be back on track (`./bw-dev makemigrations --merge`).

2022-12-17 23:32 UTC, Giebisch commented
> Sorry for making your tests even more busted with that commit! I believe all you need to do is create a merge migration to be back on track (`./bw-dev makemigrations --merge`).

Just to be clear, the commit is there so we will have consistent migrations, right ? ^^

2022-12-18 16:00 UTC, mouse-reeve commented
Creating a merge migration just tells Django how to step through the list of migrations in the right order. Does that answer your question? I'm not sure I know exactly what you're asking

2022-12-18 18:07 UTC, Giebisch commented
@mouse-reeve Ah perhaps I have not expressed myself precisely enough. What was the reason to sync the `main` branch into this one at the current state ? The way I know it is that you don't do it until you've finished developing. That's why I'm asking, maybe this has something to do with the migration files ?

2022-12-19 03:35 UTC, mouse-reeve commented
Ah I see - I merged in `main` because there was a merge conflict related to a different PR which I merged, and I wanted to resolve it so that you wouldn't have to.

2022-12-19 20:52 UTC, Giebisch commented
I believe the 2 failed tests have nothing to do with my changes, but I'm not 100% sure

2022-12-25 16:07 UTC, Giebisch commented
@mouse-reeve Okay looks like something did indeed go wrong with the migrations. Can you check again if everything was correct with your commit ? Might need your help here

2022-12-30 15:30 UTC, mouse-reeve commented
It looks like it still wants a merge migration, even though I see you made one above. Is it possible that you ran the merge before pulling the latest `main` into your branch? I think if you
 - Migrate back to the migration before your merge (`./bw-dev migrate bookwyrm 0170`)
 - Delete the 0171 merge migration
 - Merge `main` into you branch
 - Re-run the merge migration
That should fix it?

2023-01-02 16:43 UTC, Giebisch commented
@mouse-reeve Thanks, I think that solved the problem.

2023-01-10 04:18 UTC, mouse-reeve requested changes
I haven't gotten a chance to properly test this, but I'm excited to have it as a feature! For now, just a couple places that need translation support ❤️

2023-01-10 04:18 UTC, mouse-reeve commented on bookwyrm/templates/import/import.html
> +                <p>Currently you are allowed to import {{ import_size_limit }} books every {{ import_limit_reset }} days.</p>
These blocks of text will need to be wrapped in `{% blocktrans %]` tags so they can be localized. For example:
```
<p>{% blocktrans %}Currently you are allowed to import {{ import_size_limit }} books every {{ import_limit_reset }} days.{% endblocktrans %}</p>
```

2023-01-10 04:18 UTC, mouse-reeve commented on bookwyrm/templates/settings/imports/imports.html
> +                <label for="limit">Set import limit to</label>
This needs to be in a `{% trans "..." %}` tag

2023-01-11 15:01 UTC, Giebisch commented
Not sure why the tests are failing now, works for me locally and obviously I haven't touched anything besides the two templates. Can you have a look @mouse-reeve ? Much appreciated! :)

2023-01-11 15:09 UTC, mouse-reeve commented
The merge migrations are at it again! I guess it's because there are new migrations on main, and the tests must be merging before they run? If you merge main into your branch and create another merge migration, that should fix it.

2023-01-11 18:55 UTC, mouse-reeve requested changes
This worked great for regular imports, but it misses retry imports, which allowed me to overshoot my limit by 200 books

2023-01-17 00:22 UTC, Giebisch commented
Great catch! Fixed it :)

2023-01-19 19:16 UTC, mouse-reeve approved these changes
Looks good!

2023-01-19 19:16 UTC, merged