Remove redundant DB queries
bookwyrm-social/bookwyrm pull request #2636
Opened 2023-01-29 18:00 UTC by 0x29a

This PR downs the number of DB requests from 46 to 38 for the feed page, assuming you have 3 books added to each shelve (`to-read`, `reading`, `read`). Also, it fixes one duplicated request from the book page.

Testing steps:
1. Switch to the `main` branch.
2. Cherry-pick ee3c29f9a269b8aa7dbd218be895e59b1fad3270 and fd98aa34a6ff2ae7325bea64af2463db5d5b09eb
3. Add three test books, each to it's own shelve.
4. Note the number of DB requests.
5. Rebase on `redundant-db-queries`.
6. There should be 8 less DB requests now.
7. Test that book suggestions block works well.
8. Test that book page works well too.

2023-01-29 21:22 UTC, chdorner requested changes
These performance improvements are great, thank you so much!

There's probably a small mistake in the logic in `get_suggested_books`, it behaves differently now when changing up the number of books on a user's shelves.

It works great with 1 book per shelf as described in the PR description, but trying to shake things up a bit I tested with 5 to-read, 2 reading, and 3 read.

On `main` I get (in order):
* 2x reading
* 2x read
* 1x to-read

on this PR I get (also in order):
* 5x to-read
(no books from reading or read)

2023-01-29 22:24 UTC, 0x29a commented
Ah, right, `user_shelves` seem to be losing the original ordering. I should have tested this on a bigger set of books. :disappointed:  Thank you for the review and catching this, @chdorner, I'll fix this sometime tomorrow.

2023-01-30 05:57 UTC, 0x29a commented
@chdorner, should be fixed now.

2023-01-30 16:57 UTC, chdorner approved these changes
Thank you so much for these performance improvements! 🚤 

The book suggestions are now following the same shelf ordering as on `main`, but with less queries :raised_hands:

2023-01-30 17:03 UTC, merged

2023-01-31 06:46 UTC, 0x29a commented
Thanks for the review, @chdorner!