Replace docker-compose with compose V2 call
bookwyrm-social/bookwyrm pull request #2781
Opened 2023-04-05 09:55 UTC by Neriderc

Replaced compose V1 'docker-compose' with compose V2s 'docker compose'

Docker is removing support for docker-compose, and it doesn't appear to be possible to install it anymore. Instead, it has been replaced with compose V2 which is a docker plugin called with 'docker compose' (no hyphen). [More info](https://docs.docker.com/compose/compose-v2/).

This pull request replaces all instances of 'docker-compose' with 'docker compose' exclusively within bw-dev.

2023-04-11 16:22 UTC, WesleyAC requested changes
Thanks for finding this!

I think it would be preferable to check if `docker compose` is installed, but fall back to `docker-compose` and give a warning if not, given that older installs are likely to not have the compose plugin.

2023-04-11 20:22 UTC, Neriderc commented
> Thanks for finding this!
> 
> I think it would be preferable to check if `docker compose` is installed, but fall back to `docker-compose` and give a warning if not, given that older installs are likely to not have the compose plugin.

I'm afraid I'm not familiar enough with how to do that. @jaschaurbach asked on the matrix chat if I could do a pull request with this change since it worked for me, but I'm no expert. Probably better for someone else to do, or if you have info or an example you could point me at I can give it a go.

2023-04-12 01:46 UTC, WesleyAC commented
No worries! I can make the change.

2023-04-12 01:54 UTC, WesleyAC commented
Sent #2814 for this, so I'm going to go ahead and close this. Thanks again for reporting it!

2023-04-12 01:54 UTC, closed without merging